"""empty message

Revision ID: 7ef25971fd6f
Revises: 56cc32caf2c9
Create Date: 2020-05-17 08:50:07.668665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ef25971fd6f'
down_revision = '56cc32caf2c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('pword_h', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=64), nullable=True))
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'pword_h')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
